### ISSUE TITLE
Unable to analyze 4GB dumps of 32-bit processes

### ISSUE THREAD

**Issue by swift-kim** [microsoft/clrmd#402]
It seems ClrMD is not able to process 32-bit memory dumps larger than 2GB due to inconsistent address conversion between coreclr and ClrMD.

As @leculver and @mikem8361 already discussed in #280, using `ulong` types for address values may lead to unexpected behavior on particular platforms.

For your information, I am developing for Tizen wearable devices which run 32-bit (armel) .NET processes on 64-bit Linux kernels. Unlike normal 32-bit processes on other platforms, each user process has 4GB of address space.

As far as I can see in the DAC implementation of coreclr, most of exposed address values are in `CLRDATA_ADDRESS` types, so we can safely assume them as sign-extended according to [this comment](https://github.com/dotnet/runtime/blob/20ab2fa963934b5823e0b8afbba858169dd27169/src/coreclr/src/debug/daccess/dacimpl.h#L35-L111). When the values are passed to ClrMD however, they are (implicitly) converted into `ulong` type (instead of `long`) which seems not correct for negative `CLRDATA_ADDRESS`'es.

For example, when the DAC calls into ClrMD using `DataTargetAdapter::ReadVirtual()` and the value of `address` is larger than 0x7FFFFFFF (let's say 0xFFCCBBAA), the `ulong` value passed to `DacDataTargetWrapper` appears to be super larger than expected (0xFFFFFFFFFFCCBBAA).

https://github.com/dotnet/runtime/blob/master/src/coreclr/src/debug/daccess/datatargetadapter.cpp#L186-L196

Is this conversion intentional (should I assume sign-extension for `ulong`)? Or am I missing something? 

In my experiment, my sample code (just printing a managed stakctrace) simply worked by modifying the implementation of `TO_CDADDR` macro in the coreclr runtime. I don't think this would be a right choice however. Changing all occurrences of `ulong` in the DAC interfaces of ClrMD to `long` also looks bad since we will need a lot of work to be done and additional maths in the code.

**Comment by leculver** [comment]
Thanks for bringing this to my attention.  I'm in the process of making ClrMD 2.0 and have the opportunity to make breaking changes as needed, but it's not entirely clear what should be done to fix it.  I'll try to make a test this week and see what work needs to be done, but it's a very difficult scenario to test.

> Is this conversion intentional (should I assume sign-extension for ulong)? Or am I missing something? 

Sign extension is something that happens in mscordaccore.dll (CLR's debugging implementation layer) and not something that's happening due to ClrMD.  The choice of using `ulong` throughout ClrMD was intentional to try to not introduce more sign extension issues.

You can see that for yourself by setting a breakpoint on DacDataTargetWrapper.ReadVirtual and calling:

`clrRuntime.DacLibrary.SOSDacInterface.GetMethodTableData(0xFFCCBBAA, out _);`

The address that comes out the other side has been sign extended by the dac, regardless of whether you change `GetMethodTableData` and `ReadVirtual` (and all their delegates) to use long.

> Changing all occurrences of ulong in the DAC interfaces of ClrMD to long also looks bad since we will need a lot of work to be done and additional maths in the code.

This can't be fixed by swapping ulong to long.  I think we can try to fix this by accounting for sign extension on x86 in all of the `IDataReader` and `DacDataTargetWrapper` implementations.

However, this means that ClrMD will still produce sign extended answers out for users.  For example, your `ClrThread.Address`/`StackPointer`/`InstructionPointer` might look like 0xFFFFFFFFFFCCBBAA, but the library itself would (hopefully) produce good data, like correct stack traces, heap enumeration, etc.  It will be very difficult for me to generate a sufficient test case for this though.

In any case, I will attempt to fix this in ClrMD 2.0.

**Comment by leculver** [comment]
> You might be talking about different platforms (in case it makes a difference for sign extension expectations)

Yeah, which is another reason this is difficult for me to test this.  =)

I don't have access to an x64 ARM device to put Linux on.  Right now though I think even Windows x86 is broken when you use /3gb in any case the address gets too high, so at minimum starting with fixing Windows should tell me how bad it's going to be elsewhere.

**Comment by swift-kim** [comment]
@leculver Thank you for the comments!

I managed to deal with the issue with [this](https://github.com/swift-kim/clrmd/commit/475a1da46041755c5faba0201741ac09e57864e0) (tentative) patch. I used only simple type casts in two files.

This cast (zero-extended `ulong` to sign-extended `ulong`)
```csharp
if (PointerSize == 4)
{
    ip = (ulong)(int)ip;
...
```
is the equivalent of
```cpp
#define TO_CDADDR(taddr) ((CLRDATA_ADDRESS)(LONG_PTR)(taddr))
```
in [`dacimpl.h`](https://github.com/dotnet/runtime/blob/20ab2fa963934b5823e0b8afbba858169dd27169/src/coreclr/src/debug/daccess/dacimpl.h#L56), and
```csharp
position = IntPtr.Size == 4 ? (uint)position : position;
```
does the opposite (=`CLRDATA_ADDRESS_TO_TADDR`).

The result of running a simple [sample program](https://github.com/swift-kim/ClrMDSample) on Tizen armel looks like:

```
Found CLR Version: v0.0.0.00
DAC location: /tmp/clrmd2048/libmscordaccore.so
AppDomains:      1
Managed Threads: 5
ID:      1
Name:    dotnet-launcher-3699
Address: FFFFFFFFF7827800
Module:  F0745000 /opt/usr/home/owner/share/tmp/sdk_tools/clrmd/System.Private.CoreLib.dll
...
Module:  E45FD000 /opt/usr/home/owner/share/tmp/sdk_tools/clrmd/System.Collections.Concurrent.dll
Module:  E3D7B000 /opt/usr/home/owner/share/tmp/sdk_tools/clrmd/System.Threading.Timer.dll
Thread E73:
FFFFFFFFFFD62C7C            0 [InlinedCallFrame]
FFFFFFFFFFD62C7C            0 [InlinedCallFrame]
FFFFFFFFFFD62C78 FFFFFFFFEB95EE59 ILStubClass.IL_STUB_PInvoke(Int32, System.String[], UIAppLifecycleCallbacks ByRef, IntPtr)
FFFFFFFFFFD62D28 FFFFFFFFEB92EE1D Tizen.Applications.CoreBackend.UICoreBackend.Run(System.String[])
FFFFFFFFFFD62DE0 FFFFFFFFEB92E71D Tizen.Applications.CoreApplication.Run(System.String[])
FFFFFFFFFFD62E98 FFFFFFFFEB92D7C1 Tizen.Applications.CoreUIApplication.Run(System.String[])
FFFFFFFFFFD62EE0 FFFFFFFFEF369303 /proc/self/fd/32/bin/Alarm.dll!Unknown
FFFFFFFFFFD630C4            0 [GCFrame]
FFFFFFFFFFD63458            0 [GCFrame]

Thread E80:
FFFFFFFFF14FDAA8            0 [DebuggerU2MCatchHandlerFrame]

Thread E84:

Thread E86:

Thread E95:
```

Also tested for:
- RPi3 (armhf 32-bit Linux, 2GB user space)
- Desktop (Linux x64)

The SOS hosting (`dotnet-dump analyze`) in [diagnostics](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md) also works well on Tizen with the new ClrMD binary.

```
Loading core dump: /tmp/coredump.3699 ...
Ready to process analysis commands. Type 'help' to list available commands or 'help [command]' to get detailed help on a command.
Type 'quit' or 'exit' to exit the session.
> clrstack
OS Thread Id: 0xe73 (0)
Child SP       IP Call Site
FFD62C7C f6e00038 [InlinedCallFrame: ffd62c7c]
FFD62C7C eb95ee58 [InlinedCallFrame: ffd62c7c] Interop+Application.Main(Int32, System.String[], UIAppLifecycleCallbacks ByRef, IntPtr)
FFD62C78 EB95EE58 ILStubClass.IL_STUB_PInvoke(Int32, System.String[], UIAppLifecycleCallbacks ByRef, IntPtr)
FFD62D28 EB92EE1C Tizen.Applications.CoreBackend.UICoreBackend.Run(System.String[])
FFD62DE0 EB92E71C Tizen.Applications.CoreApplication.Run(System.String[])
FFD62E98 EB92D7C0 Tizen.Applications.CoreUIApplication.Run(System.String[])
FFD62EE0 EF369302 /proc/self/fd/32/bin/Alarm.dll!Unknown
FFD630C4 f51ff2ae [GCFrame: ffd630c4]
FFD63458 f51ff2ae [GCFrame: ffd63458]
```

I wonder if you have any better idea. (I really don't know the full internal details of ClrMD.) If this is an applicable change, is there any other place to put the casts?

**Comment by weltkante** [comment]
Just a side note, I consider `ip = (ulong)(int)ip;` to be unreadable. The int-to-ulong cast changes two properties of the number where order matters but is not obvious from source, unless you are a language expert you have to do a random guess what it does, whether the widening or the change to unsigned happens first (i.e. it may or may not be sign extended).

**Comment by swift-kim** [comment]
@weltkante Right. It should be more clear. Maybe we should add inline annotations or make it as a named function.

@leculver By the way, if you are to test any code on ARM, I think @mikem8361 had a similar testing environment before according to https://github.com/dotnet/coreclr/issues/25707.

**Comment by swift-kim** [comment]
https://github.com/microsoft/clrmd/blob/32643cc295897dfb49abaf1594d1490dc30cfbf4/src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopThread.cs#L126-L154

This stackwalk operation in `DesktopThread.InitLocalData()` looks similar to the one in `DesktopRuntimeBase.EnumerateStackFrames()` from my patch. But the method is never used by anything. Am I supposed to fix it as well?

**Comment by leculver** [comment]
Sorry for the delay.  I am taking a look at this now and I will likely have a pull request ready (for 2.0) by tonight or tomorrow for review.

I'd like to approach this in a more methodical way to fix it for the entire library and not try to spot-fix the specific locations that make it work for this specific problem.  I won't be able to test this fully on arm64 this week, but hopefully you can try it out and let me know if it works.

**Comment by leculver** [comment]
@swift-kim PR #419 is more in the direction I want to go to solve this issue.  Can you give this a try and see if it helps?

Everywhere that the dac would produce a CLRDATA_ADDRESS (signed 64 bit integer) has been marked with a [ClrDataAddress](https://github.com/leculver/clrmd/blob/sign_extension/src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataAddress.cs) struct.  For example, instead of trying to manually fixup pointers, we simply let this struct auto-convert the values to ulong: https://github.com/leculver/clrmd/commit/01dfd8a1d0f11f1bdf323e428ef1d8bad429fbb9#diff-7709dce4340a4954991dfd9709794d37L13-L72.

The idea is that everywhere within ClrMD (and when we pass the value out to the user via public properties) should see the non-sign extended values.  This also means we shouldn't need to do any conversions when calling out to IDataReader implementations.

Let me know if there's something that I missed in this change where it doesn't work in your scenario.  I won't be able to get around to testing this until late next week at the earliest.

**Comment by swift-kim** [comment]
@leculver The use of overator overloading looks interesting. I'll give it a try after switching over to ClrMD2.0. Thank you for your work!

**Comment by swift-kim** [comment]
@leculver It seems the issue is not fully resolved by #419. A DacError is encountered at the Dac side when `GetFrameName()` is invoked for special frames.

As I mentioned in https://github.com/microsoft/clrmd/pull/419#discussion_r357910098, the args passed to the Dac also should be in ClrDataAddress type (otherwise at least a signed type), like https://github.com/swift-kim/clrmd/commit/acbcc790d9541ede753ece793f2981f721dd6ecd. Do you want me to make changes or want to debug it yourself?

**Comment by leculver** [comment]
I'm sorry, I just haven't had a chance to get to this.  I am leaving on vacation on Friday and I'm running out of time to get everything done.

I saw the comment you left there about other places we need ClrDataAddress.  You are right but I haven't gotten to changing it yet.  You are always welcome to open a pull request if you figure something out and can fix it before I do.

As for this specific problem with `GetFrameName` and the Free MethodTable issue...unfortunately I haven't had a chance to debug it yet.  I'm still planning to try before the end of the week, if I can, but once my vacation is here I won't be able to write code myself.  Sorry for the delay.  It's just a crazy week since I have to wrap up a lot of things before going on vacation.

**Comment by leculver** [comment]
Regarding the issue with failing to create a Free method table, here's the program I tested:

```
using ClrRuntime runtime = dataTarget.ClrVersions.Single().CreateRuntime();
using var dac = runtime.DacLibrary.SOSDacInterface;
if (!dac.GetCommonMethodTables(out CommonMethodTables mts))
    Console.WriteLine("Failed to get common method tables");
else if (!dac.GetMethodTableData(mts.FreeMethodTable, out MethodTableData data))
    Console.WriteLine("Failed to get Free MethodTableData");
else
    Console.WriteLine("Succeeded");
```

This printed "Succeeded" on an x86 and x64 raspberry pi devices:

    4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
    4.15.0-1052-raspi2 #56-Ubuntu SMP PREEMPT Tue Nov 26 15:34:44 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

I also tested this program on the same devices:

        using ClrRuntime runtime = dt.ClrVersions.Single().CreateRuntime();

        foreach (ClrThread thread in runtime.Threads)
            foreach (ClrStackFrame frame in thread.EnumerateStackTrace())
                Console.WriteLine(frame);

Both correctly print the right thing:

```
[HelperMethodFrame]
Types.Inner()
Types.Main()
[GCFrame]
[GCFrame]
[DebuggerU2MCatchHandlerFrame]
```

At this point I'm not able to reproduce the problem you are running into.  I'm asking around if we have a "Tizen wearable device" to test with, but I don't think we do.  I'm not sure what to do next...  I can probably work around the bad Free method table by creating ClrType object for Free without using the failing function...it's really tough to do that without a device to test on.

**Comment by swift-kim** [comment]
@leculver The problem is not with ClrMD and very Tizen-specific. I'll ask my team for diagnosing the problem more precisely and let you know if anything is found. Thank you very much and have a good vacation!

**Comment by leculver** [comment]
Thank you!

Please let me know what you find.  Even if it's Tizen specific we still want to know what the root cause of the problem turns out to be in case other customers run into the same problem on the same device in the future.

**Comment by swift-kim** [comment]
> The args we pass to the dac shouldn't matter. On the dac side these are going to get casted down to 32bit integers/pointers so we shouldn't need to sign extend anything ourselves.

It matters when the Dac casts the args down to 32bit pointers. It fails in `CLRDATA_ADDRESS_TO_TADDR()` in [`dacimpl.h`](https://github.com/dotnet/runtime/blob/20ab2fa963934b5823e0b8afbba858169dd27169/src/coreclr/src/debug/daccess/dacimpl.h#L58-L72) bacause `iSignedAddr > INT_MAX` is true.

For example if we pass 0xffffabcd to the Dac,
- 0x00000000ffffabcd as `ulong` > `INT_MAX` (**FAIL**)

but,
- 0xffffffffffffabcd as `long`  = -0x00005433 as `int` > `-INT_MIN` (**OK**)

**Comment by leculver** [comment]
Ugh that's awful.  You are right, we'll need to wrap all parameters with ClrDataAddress or something similar.  I will work on this either tomorrow if I have some time, or when I'm back from vacation in early January.

**Comment by swift-kim** [comment]
Oh, in my guess, it should only happen with values obtained by `RuntimeBuilder.EnumerateStackTrace()` because they are not correctly sign-extended there. I'll make a PR to fix RuntimeBuilder instead of changing the whole SosDac interface.

**Comment by leculver** [comment]
@swift-kim The issue with Free MethodTable is being fixed here:  https://github.com/dotnet/runtime/pull/1086.

**Comment by swift-kim** [comment]
@leculver Great news!

**Comment by swift-kim** [comment]
@leculver Sorry to bother you again but this issue still needs a fix before being closed.

> we'll need to wrap all parameters with ClrDataAddress or something similar.

Do you have any plan on this? Just wrapping all params (in SosDac.cs, etc.) with ClrDataAddress and sign-extending them will do?

**Comment by leculver** [comment]
Can you test whether PR #535 fixes the issue or not?  I have no way to test whether my changes were correct or if I missed something.

**Comment by swift-kim** [comment]
It worked just as expected. No issues found. Thank you for your hard work!

```
Thread DBD:
    FFEE7CE0       640073 [HelperMethodFrame_1OBJ] (System.Threading.Thread.Join)
    FFEE7D78     F227A313 System.Threading.Thread.Join()
    FFEE7D80     F5BEF539 ClrMDSample.Program.Main(System.String[])
    FFEE7F14     F6F09D4F [GCFrame]
    FFEE82A8     F6F09D4F [GCFrame]

Thread DC1:
    F31FCD80       2E006D [DebuggerU2MCatchHandlerFrame]
```
